### ISSUE TITLE
THE PAPER

### ISSUE THREAD

**Issue by poemon** [JethroJames/Wind-Speed-Forecast-TCN_GRU#1]
Hello author, I would like to ask if this code is from a research paper. Could you please provide me with the link to the paper? Thank you

**Comment by JethroJames** [comment]
It was simply a part of a project and no public paper was published about it. Thank you for your attention！

**Comment by JethroJames** [comment]
Thank you all for your enthusiasm towards this project! I want to set the record straight: the project has attracted a lot of attention, but it's important to note that it's more of a preliminary investigation than a full-fledged scholarly article. The technical report is already finished. I am on the cusp of submitting it to arXiv; a step that requires some time to ensure everything is correct and complete. Once it's successfully submitted, I plan to share the code and supplementary materials on GitHub. Rest assured, I'll broadcast an update and share the relevant links there once everything is live.
